# 应用服务 WEB 访问端口
server:
  port: 8088

# 配置数据库
spring:
  datasource:
    url: jdbc:mysql://43.138.121.194:3306/online_edit?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: zzwzzw
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.back.pojo
  configuration:
      map-underscore-to-camel-case: true


